### ISSUE TITLE
Address Apple M1 Macs compatibility

### ISSUE THREAD

**Issue by chao2zhang** [detekt/detekt-intellij-plugin#158]
I was trying to publish release, but it failed to compile locally or fail the test.

Compilation failure
```
java.lang.NoClassDefFoundError: Could not initialize class com.intellij.ui.components.MacScrollBarUI$Style
        at com.intellij.ui.components.MacScrollBarUI.installUI(MacScrollBarUI.java:103)
        at java.desktop/javax.swing.JComponent.setUI(JComponent.java:688)
        at java.desktop/javax.swing.JScrollBar.setUI(JScrollBar.java:210)
        at com.intellij.ui.components.JBScrollBar.updateUI(JBScrollBar.java:88)
        at java.desktop/javax.swing.JScrollBar.<init>(JScrollBar.java:165)
        at com.intellij.ui.components.JBScrollBar.<init>(JBScrollBar.java:68)
        at com.intellij.ui.components.JBScrollBar.<init>(JBScrollBar.java:64)
        at com.intellij.ui.components.JBScrollPane.createVerticalScrollBar(JBScrollPane.java:305)
        at java.desktop/javax.swing.JScrollPane.<init>(JScrollPane.java:300)
        at java.desktop/javax.swing.JScrollPane.<init>(JScrollPane.java:324)
        at com.intellij.ui.components.JBScrollPane.<init>(JBScrollPane.java:97)
        at com.intellij.ui.ToolbarDecorator$1.<init>(ToolbarDecorator.java:406)
        at com.intellij.ui.ToolbarDecorator.createPanel(ToolbarDecorator.java:406)
        at com.intellij.openapi.vcs.configurable.IssueNavigationConfigurationPanel.<init>(IssueNavigationConfigurationPanel.java:140)
        at com.intellij.openapi.vcs.configurable.VcsManagerConfigurable.buildConfigurables(VcsManagerConfigurable.java:118)
        at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:96)
        at com.intellij.openapi.options.ex.ConfigurableWrapper$CompositeWrapper.getConfigurables(ConfigurableWrapper.java:288)
        at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurables(ShowSettingsUtilImpl.java:71)
        at com.intellij.ide.ui.search.SearchUtil.processProjectConfigurables(SearchUtil.java:52)
        at com.intellij.ide.ui.search.TraverseUIStarter.startup(TraverseUIStarter.java:98)
        at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:81)
        at com.intellij.idea.ApplicationLoader$startApp$8$1$1.run(ApplicationLoader.kt:245)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
        at com.intellij.idea.ApplicationLoader$startApp$8$1.run(ApplicationLoader.kt:244)
        at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
        at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
        at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
        at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
        at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
        at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
        at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Test failure
```
ConfiguredServiceTest > expect detekt runs successfully() FAILED
    java.lang.AssertionError: 
    Expecting actual throwable to be an instance of:
      java.lang.NoSuchMethodError
    but was:
      java.lang.ClassCastException: class org.jetbrains.kotlin.idea.KotlinFileType cannot be cast to class org.jetbrains.kotlin.com.intellij.openapi.fileTypes.FileType (org.jetbrains.kotlin.idea.KotlinFileType and org.jetbrains.kotlin.com.intellij.openapi.fileTypes.FileType are in unnamed module of loader 'app')
    	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerApplicationServices(KotlinCoreEnvironment.kt:685)
    	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createApplicationEnvironment(KotlinCoreEnvironment.kt:595)
    	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.getOrCreateApplicationEnvironment(KotlinCoreEnvironment.kt:548)
    	...(111 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
        at io.gitlab.arturbosch.detekt.idea.ConfiguredServiceTest.expect detekt runs successfully(ConfiguredServiceTest.kt:73)
```
https://github.com/detekt/detekt-intellij-plugin/runs/6115732175?check_suite_focus=true

**Comment by chao2zhang** [comment]
Looks like the reason is that only `kotlin-stdlib-jdk8` is pulled to 1.6.20

<img width="814" alt="image" src="https://user-images.githubusercontent.com/1175468/164950970-12902178-91db-4979-af88-e0b584ea7528.png">

**Comment by chao2zhang** [comment]
Addressed in https://github.com/detekt/detekt-intellij-plugin/commit/c5ddccf8204c555b3d5118133c37fc262050621b by updating the unit tests and manually verify through `./gradlew runIde`
