### ISSUE TITLE
org.jetbrains.kotlin.utils.KotlinExceptionWithAttachments

### ISSUE THREAD

**Issue by rocketraman** [detekt/detekt-intellij-plugin#225]
## Bug description
I selected a block of code, including its kdoc declaration and then duplicated it with ctrl-d.

## Environment
- detekt Idea Version: 1.21.0
- Platform Version: 2022.2
- Platform Vendor: JetBrains s.r.o.
- Java Version: 17.0.3
- OS Name: Linux

## Stacktrace

```
org.jetbrains.kotlin.utils.KotlinExceptionWithAttachments
	at org.jetbrains.kotlin.idea.quickfix.createFromUsage.callableBuilder.TypeInfo$ByExpression.getPossibleTypes(CallableInfo.kt:56)
	at org.jetbrains.kotlin.idea.quickfix.createFromUsage.createVariable.CreateParameterFromUsageFix$Companion$createFixForPrimaryConstructorPropertyParameter$1.invoke(CreateParameterFromUsageFix.kt:121)
	at org.jetbrains.kotlin.idea.quickfix.createFromUsage.createVariable.CreateParameterFromUsageFix$Companion$createFixForPrimaryConstructorPropertyParameter$1.invoke(CreateParameterFromUsageFix.kt:89)
	at org.jetbrains.kotlin.idea.quickfix.createFromUsage.createVariable.CreateParameterFromUsageFix.parameterData(CreateParameterFromUsageFix.kt:70)
	at org.jetbrains.kotlin.idea.quickfix.createFromUsage.createVariable.CreateParameterFromUsageFix.parameterInfo(CreateParameterFromUsageFix.kt:30)
	at org.jetbrains.kotlin.idea.quickfix.createFromUsage.createVariable.CreateParameterFromUsageFix.access$parameterInfo(CreateParameterFromUsageFix.kt:23)
	at org.jetbrains.kotlin.idea.quickfix.createFromUsage.createVariable.CreateParameterFromUsageFix$calculatedText$2.invoke(CreateParameterFromUsageFix.kt:36)
	at org.jetbrains.kotlin.idea.quickfix.createFromUsage.createVariable.CreateParameterFromUsageFix$calculatedText$2.invoke(CreateParameterFromUsageFix.kt:23)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.idea.quickfix.createFromUsage.createVariable.CreateParameterFromUsageFix.getCalculatedText(CreateParameterFromUsageFix.kt)
	at org.jetbrains.kotlin.idea.quickfix.createFromUsage.createVariable.CreateParameterFromUsageFix.getText(CreateParameterFromUsageFix.kt:52)
	at org.jetbrains.kotlin.idea.quickfix.QuickFixWithDelegateFactory.<init>(QuickFixWithDelegateFactory.kt:26)
	at org.jetbrains.kotlin.idea.quickfix.QuickFixWithDelegateFactoryKt.QuickFixWithDelegateFactory(QuickFixWithDelegateFactory.kt:78)
	at org.jetbrains.kotlin.idea.quickfix.createFromUsage.createCallable.CreateCallableMemberFromUsageFactory.newCallableQuickFix(CreateCallableMemberFromUsageFactory.kt:23)
	at org.jetbrains.kotlin.idea.quickfix.createFromUsage.createCallable.CreateCallableMemberFromUsageFactory.createFixes(CreateCallableMemberFromUsageFactory.kt:43)
	at org.jetbrains.kotlin.idea.quickfix.KotlinIntentionActionFactoryWithDelegate.doCreateActions(KotlinIntentionActionFactoryWithDelegate.kt:57)
	at org.jetbrains.kotlin.idea.quickfix.KotlinIntentionActionsFactory.createActions(KotlinIntentionActionsFactory.kt:39)
	at org.jetbrains.kotlin.idea.quickfix.KotlinIntentionActionsFactory.createActionsForAllProblems(KotlinIntentionActionsFactory.kt:21)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitorKt.createQuickFixes(AbstractKotlinHighlightVisitor.kt:338)
	at org.jetbrains.kotlin.idea.highlighter.ElementAnnotator.createFixesMap(ElementAnnotator.kt:183)
	at org.jetbrains.kotlin.idea.highlighter.ElementAnnotator.createFixesMap$default(ElementAnnotator.kt:178)
	at org.jetbrains.kotlin.idea.highlighter.ElementAnnotator.registerDiagnosticsSameFactoryQuickFixes(ElementAnnotator.kt:80)
	at org.jetbrains.kotlin.idea.highlighter.ElementAnnotator.registerDiagnosticsQuickFixes(ElementAnnotator.kt:73)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitor.annotateQuickFixes(AbstractKotlinHighlightVisitor.kt:222)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitor.analyze(AbstractKotlinHighlightVisitor.kt:157)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitor.analyze(AbstractKotlinHighlightVisitor.kt:63)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:276)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:221)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:101)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.visitInlinedFunction(ControlFlowProcessor.kt:1061)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.visitFunction(ControlFlowProcessor.kt:1050)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.visitLambdaExpression(ControlFlowProcessor.kt:1092)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitLambdaExpression(KtVisitorVoid.java:799)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitLambdaExpression(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtLambdaExpression.accept(KtLambdaExpression.java:40)
	at org.jetbrains.kotlin.psi.KtLambdaExpression.accept(KtLambdaExpression.java:92)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.generateInstructions(ControlFlowProcessor.kt:180)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.visitCallExpression(ControlFlowProcessor.kt:1125)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitCallExpression(KtVisitorVoid.java:811)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitCallExpression(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtCallExpression.accept(KtCallExpression.java:35)
	at org.jetbrains.kotlin.psi.KtElementImpl.accept(KtElementImpl.java:51)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.generateInstructions(ControlFlowProcessor.kt:180)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.visitQualifiedExpression(ControlFlowProcessor.kt:1105)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitQualifiedExpression(KtVisitorVoid.java:823)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitQualifiedExpression(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtVisitor.visitDotQualifiedExpression(KtVisitor.java:306)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitDotQualifiedExpression(KtVisitorVoid.java:293)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitDotQualifiedExpression(KtVisitorVoid.java:847)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitDotQualifiedExpression(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtDotQualifiedExpression.accept(KtDotQualifiedExpression.kt:32)
	at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:49)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.generateInstructions(ControlFlowProcessor.kt:180)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.visitIfExpression(ControlFlowProcessor.kt:564)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitIfExpression(KtVisitorVoid.java:757)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitIfExpression(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtIfExpression.accept(KtIfExpression.java:33)
	at org.jetbrains.kotlin.psi.KtElementImpl.accept(KtElementImpl.java:51)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.generateInstructions(ControlFlowProcessor.kt:180)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.visitBlockExpression(ControlFlowProcessor.kt:1026)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitBlockExpression(KtVisitorVoid.java:865)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitBlockExpression(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtBlockExpression.accept(KtBlockExpression.java:79)
	at org.jetbrains.kotlin.psi.KtBlockExpression.accept(KtBlockExpression.java:86)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.generateInstructions(ControlFlowProcessor.kt:180)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.visitIfExpression(ControlFlowProcessor.kt:570)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitIfExpression(KtVisitorVoid.java:757)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitIfExpression(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtIfExpression.accept(KtIfExpression.java:33)
	at org.jetbrains.kotlin.psi.KtElementImpl.accept(KtElementImpl.java:51)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.generateInstructions(ControlFlowProcessor.kt:180)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.visitBlockExpression(ControlFlowProcessor.kt:1026)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitBlockExpression(KtVisitorVoid.java:865)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitBlockExpression(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtBlockExpression.accept(KtBlockExpression.java:79)
	at org.jetbrains.kotlin.psi.KtBlockExpression.accept(KtBlockExpression.java:86)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.generateInstructions(ControlFlowProcessor.kt:180)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor.generate(ControlFlowProcessor.kt:93)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor.processLocalDeclaration(ControlFlowProcessor.kt:119)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor.access$processLocalDeclaration(ControlFlowProcessor.kt:70)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.visitFunction(ControlFlowProcessor.kt:1048)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.visitLambdaExpression(ControlFlowProcessor.kt:1092)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitLambdaExpression(KtVisitorVoid.java:799)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitLambdaExpression(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtLambdaExpression.accept(KtLambdaExpression.java:40)
	at org.jetbrains.kotlin.psi.KtLambdaExpression.accept(KtLambdaExpression.java:92)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.generateInstructions(ControlFlowProcessor.kt:180)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.generateValueArgument(ControlFlowProcessor.kt:1681)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.generateCall(ControlFlowProcessor.kt:1580)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.checkAndGenerateCall(ControlFlowProcessor.kt:1564)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.generateCall(ControlFlowProcessor.kt:1559)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.visitCallExpression(ControlFlowProcessor.kt:1120)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitCallExpression(KtVisitorVoid.java:811)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitCallExpression(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtCallExpression.accept(KtCallExpression.java:35)
	at org.jetbrains.kotlin.psi.KtElementImpl.accept(KtElementImpl.java:51)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.generateInstructions(ControlFlowProcessor.kt:180)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.visitQualifiedExpression(ControlFlowProcessor.kt:1105)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitQualifiedExpression(KtVisitorVoid.java:823)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitQualifiedExpression(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtVisitor.visitDotQualifiedExpression(KtVisitor.java:306)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitDotQualifiedExpression(KtVisitorVoid.java:293)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitDotQualifiedExpression(KtVisitorVoid.java:847)
	at org.jetbrains.kotlin.psi.KtVisitorVoid.visitDotQualifiedExpression(KtVisitorVoid.java:21)
	at org.jetbrains.kotlin.psi.KtDotQualifiedExpression.accept(KtDotQualifiedExpression.kt:32)
	at org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:49)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor$CFPVisitor.generateInstructions(ControlFlowProcessor.kt:180)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor.generate(ControlFlowProcessor.kt:93)
	at org.jetbrains.kotlin.cfg.ControlFlowProcessor.generatePseudocode(ControlFlowProcessor.kt:78)
	at org.jetbrains.kotlin.cfg.pseudocode.PseudocodeUtil.generatePseudocode(PseudocodeUtil.java:99)
	at org.jetbrains.kotlin.cfg.pseudocode.PseudocodeUtilsKt.getContainingPseudocode(pseudocodeUtils.kt:290)
	at org.jetbrains.kotlin.cfg.pseudocode.PseudocodeUtilsKt.getContainingPseudocode(pseudocodeUtils.kt:294)
	at org.jetbrains.kotlin.idea.quickfix.createFromUsage.callableBuilder.CallableBuilder$pseudocode$2.invoke(CallableBuilder.kt:151)
	at org.jetbrains.kotlin.idea.quickfix.createFromUsage.callableBuilder.CallableBuilder$pseudocode$2.invoke(CallableBuilder.kt:133)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.idea.quickfix.createFromUsage.callableBuilder.CallableBuilder.getPseudocode(CallableBuilder.kt)
	at org.jetbrains.kotlin.idea.quickfix.createFromUsage.callableBuilder.TypeInfo$ByExpression.getPossibleTypes(CallableInfo.kt:46)
	... 52 more
```

**Comment by rocketraman** [comment]
Probably another instance of https://github.com/detekt/detekt-intellij-plugin/issues/271.
