### ISSUE TITLE
org.jetbrains.kotlin.utils.KotlinExceptionWithAttachments: Exception while analyzing expression at (1,1) in DummyHolder

### ISSUE THREAD

**Issue by subhash-v** [detekt/detekt-intellij-plugin#426]

**Comment by subhash-v** [comment]
# Stacktrace

```
org.jetbrains.kotlin.utils.KotlinExceptionWithAttachments: Exception while analyzing expression at (1,1) in DummyHolder
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.logOrThrowException(ExpressionTypingVisitorDispatcher.java:246)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.lambda$getTypeInfo$0(ExpressionTypingVisitorDispatcher.java:224)
	at org.jetbrains.kotlin.util.PerformanceCounter.time(PerformanceCounter.kt:101)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.getTypeInfo(ExpressionTypingVisitorDispatcher.java:164)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.getTypeInfo(ExpressionTypingVisitorDispatcher.java:134)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.getTypeInfo(ExpressionTypingVisitorDispatcher.java:146)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingServices.getTypeInfo(ExpressionTypingServices.java:120)
	at org.jetbrains.kotlin.idea.analysis.AnalyzerUtilKt.computeTypeInfoInContext(AnalyzerUtil.kt:40)
	at org.jetbrains.kotlin.idea.analysis.AnalyzerUtilKt.analyzeInContext(AnalyzerUtil.kt:57)
	at org.jetbrains.kotlin.idea.analysis.AnalyzerUtilKt.analyzeInContext$default(AnalyzerUtil.kt:110)
	at org.jetbrains.kotlin.idea.analysis.AnalyzerUtilKt.analyzeAsReplacement(AnalyzerUtil.kt:86)
	at org.jetbrains.kotlin.idea.analysis.AnalyzerUtilKt.analyzeAsReplacement(AnalyzerUtil.kt:105)
	at org.jetbrains.kotlin.idea.analysis.AnalyzerUtilKt.analyzeAsReplacement$default(AnalyzerUtil.kt:102)
	at org.jetbrains.kotlin.idea.core.ShortenReferences$ShortenQualifiedExpressionsProcessor.copyShortenAndAnalyze(ShortenReferences.kt:678)
	at org.jetbrains.kotlin.idea.core.ShortenReferences$ShortenQualifiedExpressionsProcessor.analyzeQualifiedElement(ShortenReferences.kt:569)
	at org.jetbrains.kotlin.idea.core.ShortenReferences$ShortenQualifiedExpressionsProcessor.analyzeQualifiedElement(ShortenReferences.kt:534)
	at org.jetbrains.kotlin.idea.core.ShortenReferences$ShorteningProcessor.analyzeCollectedElements(ShortenReferences.kt:364)
	at org.jetbrains.kotlin.idea.core.ShortenReferences$shortenReferencesInFile$$inlined$runReadAction$2.compute(actions.kt:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:841)
	at org.jetbrains.kotlin.idea.core.ShortenReferences.shortenReferencesInFile(ShortenReferences.kt:833)
	at org.jetbrains.kotlin.idea.core.ShortenReferences.process(ShortenReferences.kt:183)
	at org.jetbrains.kotlin.idea.core.ShortenReferences.process(ShortenReferences.kt:105)
	at org.jetbrains.kotlin.idea.core.ShortenReferences.process(ShortenReferences.kt:113)
	at org.jetbrains.kotlin.idea.core.ShortenReferences.process$default(ShortenReferences.kt:109)
	at org.jetbrains.kotlin.idea.completion.CompletionUtilsKt.shortenReferences(CompletionUtils.kt:364)
	at org.jetbrains.kotlin.idea.completion.handlers.KotlinCallableInsertHandler.addImport(KotlinCallableInsertHandler.kt:55)
	at org.jetbrains.kotlin.idea.completion.handlers.KotlinCallableInsertHandler.handleInsert(KotlinCallableInsertHandler.kt:29)
	at org.jetbrains.kotlin.idea.completion.handlers.KotlinFunctionInsertHandler.handleInsert(KotlinFunctionInsertHandler.kt:226)
	at org.jetbrains.kotlin.idea.completion.handlers.KotlinFunctionInsertHandler$Normal.handleInsert(KotlinFunctionInsertHandler.kt:60)
	at com.intellij.codeInsight.lookup.LookupElementBuilder.handleInsert(LookupElementBuilder.java:397)
	at com.intellij.codeInsight.lookup.LookupElementDecorator.handleInsert(LookupElementDecorator.java:59)
	at org.jetbrains.kotlin.idea.completion.JustTypingLookupElementDecorator.handleInsert(LookupElementsCollector.kt:150)
	at com.intellij.codeInsight.lookup.LookupElementDecorator.handleInsert(LookupElementDecorator.java:59)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$insertItem$15(CodeCompletionHandlerBase.java:690)
	at com.intellij.util.indexing.FileBasedIndex.lambda$ignoreDumbMode$0(FileBasedIndex.java:163)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:588)
	at com.intellij.util.indexing.FileBasedIndex.ignoreDumbMode(FileBasedIndex.java:162)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:43)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$insertItem$16(CodeCompletionHandlerBase.java:689)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:936)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.insertItem(CodeCompletionHandlerBase.java:673)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doInsertItem$12(CodeCompletionHandlerBase.java:598)
	at com.intellij.openapi.editor.impl.CaretModelImpl.lambda$runForEachCaret$3(CaretModelImpl.java:312)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:421)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:321)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:296)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.doInsertItem(CodeCompletionHandlerBase.java:588)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.insertItemHonorBlockSelection(CodeCompletionHandlerBase.java:548)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lookupItemSelected(CodeCompletionHandlerBase.java:494)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.itemSelected(CompletionProgressIndicator.java:180)
	at com.intellij.codeInsight.completion.BaseCompletionLookupArranger.itemSelected(BaseCompletionLookupArranger.java:227)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.fireItemSelected(LookupImpl.java:926)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookupInWritableFile(LookupImpl.java:580)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.lambda$finishLookup$5(LookupImpl.java:538)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:207)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookup(LookupImpl.java:538)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookup(LookupImpl.java:523)
	at com.intellij.codeInsight.lookup.impl.actions.ChooseItemAction$Handler.lambda$doExecute$0(ChooseItemAction.java:72)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:152)
	at com.intellij.codeInsight.lookup.impl.actions.ChooseItemAction$Handler.doExecute(ChooseItemAction.java:72)
	at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.doExecute(DynamicEditorActionHandler.java:60)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:199)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:89)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:198)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:89)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:98)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:73)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:563)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$8(IdeKeyEventDispatcher.java:675)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:668)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:603)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:574)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:457)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:450)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:218)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:798)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: Unsupported descriptor type to build star projection type based on type parameters of it
	at org.jetbrains.kotlin.types.StarProjectionImplKt.starProjectionType(StarProjectionImpl.kt:78)
	at org.jetbrains.kotlin.types.StarProjectionImpl$_type$2.invoke(StarProjectionImpl.kt:35)
	at org.jetbrains.kotlin.types.StarProjectionImpl$_type$2.invoke(StarProjectionImpl.kt:34)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at org.jetbrains.kotlin.types.StarProjectionImpl.get_type(StarProjectionImpl.kt:34)
	at org.jetbrains.kotlin.types.StarProjectionImpl.getType(StarProjectionImpl.kt:38)
	at org.jetbrains.kotlin.types.TypeProjectionBase.hashCode(TypeProjectionBase.java:49)
	at java.base/java.util.ArrayList.hashCodeRange(ArrayList.java:627)
	at java.base/java.util.ArrayList.hashCode(ArrayList.java:614)
	at org.jetbrains.kotlin.types.KotlinType.computeHashCode(KotlinType.kt:95)
	at org.jetbrains.kotlin.types.KotlinType.hashCode(KotlinType.kt:105)
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateToSuperType(AbstractTypeApproximator.kt:590)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateCapturedType(AbstractTypeApproximator.kt:283)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateTo(AbstractTypeApproximator.kt:332)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateSimpleToSubType(AbstractTypeApproximator.kt:306)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.access$approximateSimpleToSubType(AbstractTypeApproximator.kt:14)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator$referenceApproximateToSubType$1.invoke(AbstractTypeApproximator.kt:27)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator$referenceApproximateToSubType$1.invoke(AbstractTypeApproximator.kt:27)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateTo(AbstractTypeApproximator.kt:116)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateToSubType(AbstractTypeApproximator.kt:99)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateParametrizedType(AbstractTypeApproximator.kt:528)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateTo(AbstractTypeApproximator.kt:315)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateSimpleToSuperType(AbstractTypeApproximator.kt:303)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.access$approximateSimpleToSuperType(AbstractTypeApproximator.kt:14)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator$referenceApproximateToSuperType$1.invoke(AbstractTypeApproximator.kt:25)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator$referenceApproximateToSuperType$1.invoke(AbstractTypeApproximator.kt:25)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateTo(AbstractTypeApproximator.kt:116)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateToSuperType(AbstractTypeApproximator.kt:88)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateCapturedType(AbstractTypeApproximator.kt:287)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateTo(AbstractTypeApproximator.kt:332)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateSimpleToSuperType(AbstractTypeApproximator.kt:303)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.access$approximateSimpleToSuperType(AbstractTypeApproximator.kt:14)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator$referenceApproximateToSuperType$1.invoke(AbstractTypeApproximator.kt:25)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator$referenceApproximateToSuperType$1.invoke(AbstractTypeApproximator.kt:25)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateTo(AbstractTypeApproximator.kt:116)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateToSuperType(AbstractTypeApproximator.kt:88)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateParametrizedType(AbstractTypeApproximator.kt:536)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateTo(AbstractTypeApproximator.kt:315)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateSimpleToSuperType(AbstractTypeApproximator.kt:303)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.access$approximateSimpleToSuperType(AbstractTypeApproximator.kt:14)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator$referenceApproximateToSuperType$1.invoke(AbstractTypeApproximator.kt:25)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator$referenceApproximateToSuperType$1.invoke(AbstractTypeApproximator.kt:25)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateTo(AbstractTypeApproximator.kt:116)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateToSuperType(AbstractTypeApproximator.kt:88)
	at org.jetbrains.kotlin.types.AbstractTypeApproximator.approximateToSuperType(AbstractTypeApproximator.kt:36)
	at org.jetbrains.kotlin.resolve.calls.inference.components.ConstraintIncorporator.approximateCapturedTypes(ConstraintIncorporator.kt:272)
	at org.jetbrains.kotlin.resolve.calls.inference.components.ConstraintIncorporator.access$approximateCapturedTypes(ConstraintIncorporator.kt:19)
	at org.jetbrains.kotlin.resolve.calls.inference.components.ConstraintIncorporator$approximateIfNeededAndAddNewConstraint$prepareType$1.invoke(ConstraintIncorporator.kt:118)
	at org.jetbrains.kotlin.resolve.calls.inference.components.ConstraintIncorporator$approximateIfNeededAndAddNewConstraint$prepareType$1.invoke(ConstraintIncorporator.kt:117)
	at org.jetbrains.kotlin.resolve.calls.inference.components.ConstraintIncorporator.approximateIfNeededAndAddNewConstraint(ConstraintIncorporator.kt:122)
	at org.jetbrains.kotlin.resolve.calls.inference.components.ConstraintIncorporator.generateNewConstraint(ConstraintIncorporator.kt:189)
	at org.jetbrains.kotlin.resolve.calls.inference.components.ConstraintIncorporator.insideOtherConstraint(ConstraintIncorporator.kt:103)
	at org.jetbrains.kotlin.resolve.calls.inference.components.ConstraintIncorporator.incorporate(ConstraintIncorporator.kt:52)
	at org.jetbrains.kotlin.resolve.calls.inference.components.ConstraintInjector.processGivenConstraints(ConstraintInjector.kt:187)
	at org.jetbrains.kotlin.resolve.calls.inference.components.ConstraintInjector.processConstraints(ConstraintInjector.kt:145)
	at org.jetbrains.kotlin.resolve.calls.inference.components.ConstraintInjector.processMissedConstraints(ConstraintInjector.kt:133)
	at org.jetbrains.kotlin.resolve.calls.inference.model.NewConstraintSystemImpl$checkMissedConstraints$errorsByMissedConstraints$1$1.invoke(NewConstraintSystemImpl.kt:390)
	at org.jetbrains.kotlin.resolve.calls.inference.model.NewConstraintSystemImpl$checkMissedConstraints$errorsByMissedConstraints$1$1.invoke(NewConstraintSystemImpl.kt:386)
	at org.jetbrains.kotlin.resolve.calls.inference.model.NewConstraintSystemImpl.runTransaction(NewConstraintSystemImpl.kt:211)
	at org.jetbrains.kotlin.resolve.calls.inference.model.NewConstraintSystemImpl.checkMissedConstraints(NewConstraintSystemImpl.kt:386)
	at org.jetbrains.kotlin.resolve.calls.inference.model.NewConstraintSystemImpl.fixVariable(NewConstraintSystemImpl.kt:363)
	at org.jetbrains.kotlin.resolve.calls.inference.components.KotlinConstraintSystemCompleter.fixVariable(KotlinConstraintSystemCompleter.kt:339)
	at org.jetbrains.kotlin.resolve.calls.inference.components.KotlinConstraintSystemCompleter.fixVariable(KotlinConstraintSystemCompleter.kt:327)
	at org.jetbrains.kotlin.resolve.calls.inference.components.KotlinConstraintSystemCompleter.fixNextReadyVariable(KotlinConstraintSystemCompleter.kt:356)
	at org.jetbrains.kotlin.resolve.calls.inference.components.KotlinConstraintSystemCompleter.runCompletion(KotlinConstraintSystemCompleter.kt:141)
	at org.jetbrains.kotlin.resolve.calls.inference.components.KotlinConstraintSystemCompleter.runCompletion(KotlinConstraintSystemCompleter.kt:37)
	at org.jetbrains.kotlin.resolve.calls.components.KotlinCallCompleter.runCompletion(KotlinCallCompleter.kt:219)
	at org.jetbrains.kotlin.resolve.calls.components.KotlinCallCompleter.runCompletion$default(KotlinCallCompleter.kt:210)
	at org.jetbrains.kotlin.resolve.calls.components.KotlinCallCompleter.runCompletion(KotlinCallCompleter.kt:207)
	at org.jetbrains.kotlin.resolve.calls.components.KotlinCallCompleter.runCompletion(KotlinCallCompleter.kt:60)
	at org.jetbrains.kotlin.resolve.calls.KotlinCallResolver.choseMostSpecific(KotlinCallResolver.kt:162)
	at org.jetbrains.kotlin.resolve.calls.KotlinCallResolver.resolveCall(KotlinCallResolver.kt:82)
	at org.jetbrains.kotlin.resolve.calls.tower.PSICallResolver.runResolutionAndInference(PSICallResolver.kt:101)
	at org.jetbrains.kotlin.resolve.calls.CallResolver.doResolveCallOrGetCachedResults(CallResolver.java:601)
	at org.jetbrains.kotlin.resolve.calls.CallResolver.lambda$computeTasksAndResolveCall$0(CallResolver.java:213)
	at org.jetbrains.kotlin.util.PerformanceCounter.time(PerformanceCounter.kt:101)
	at org.jetbrains.kotlin.resolve.calls.CallResolver.computeTasksAndResolveCall(CallResolver.java:211)
	at org.jetbrains.kotlin.resolve.calls.CallResolver.computeTasksAndResolveCall(CallResolver.java:199)
	at org.jetbrains.kotlin.resolve.calls.CallResolver.resolveSimpleProperty(CallResolver.java:140)
	at org.jetbrains.kotlin.resolve.calls.CallExpressionResolver.getVariableType(CallExpressionResolver.kt:111)
	at org.jetbrains.kotlin.resolve.calls.CallExpressionResolver.getSimpleNameExpressionTypeInfo(CallExpressionResolver.kt:146)
	at org.jetbrains.kotlin.resolve.calls.CallExpressionResolver.getSimpleNameExpressionTypeInfo(CallExpressionResolver.kt:135)
	at org.jetbrains.kotlin.types.expressions.BasicExpressionTypingVisitor.visitSimpleNameExpression(BasicExpressionTypingVisitor.java:172)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.visitSimpleNameExpression(ExpressionTypingVisitorDispatcher.java:333)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher$ForDeclarations.visitSimpleNameExpression(ExpressionTypingVisitorDispatcher.java:46)
	at org.jetbrains.kotlin.psi.KtNameReferenceExpression.accept(KtNameReferenceExpression.kt:59)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.lambda$getTypeInfo$0(ExpressionTypingVisitorDispatcher.java:175)
	... 94 more
```

**Comment by subhash-v** [comment]
- detekt Idea Version: 1.21.3-android
- Platform Version: Chipmunk | 2021.2.1 Patch 2
- Platform Vendor: JetBrains s.r.o.
- Java Version: 11.0.12
- OS Name: Mac OS X
