### ISSUE TITLE
[IDE Plugin] Stackoverflow Error

### ISSUE THREAD

**Issue by Nek-12** [detekt/detekt-intellij-plugin#478]
## Steps to Reproduce
I am not sure how to reproduce this. I'm reporting an IDE error message

## Your Environment

* Version of detekt used: 1.23.0
* Version of Gradle used (if applicable): 8.1.1
* Gradle scan link (add `--scan` option when running the gradle task): no thanks
* Operating System and version: MacOS 13.3
* Link to your project (if it's a public repository): private

```
java.lang.StackOverflowError
	at java.base/java.util.Collections$SetFromMap.isEmpty(Collections.java:5682)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runCheckCanceledHooks(ProgressManagerImpl.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:145)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:227)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getGreenStub(StubBasedPsiElementBase.java:350)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getStubOrPsiChild(StubBasedPsiElementBase.java:360)
	at org.jetbrains.kotlin.psi.KtClassOrObject.getSuperTypeList(KtClassOrObject.kt:43)
	at org.jetbrains.kotlin.psi.KtClassOrObject.getSuperTypeListEntries(KtClassOrObject.kt:45)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass$delegateExpressions$2.invoke(AbstractKotlinUClass.kt:43)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass$delegateExpressions$2.invoke(AbstractKotlinUClass.kt:42)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.getDelegateExpressions(AbstractKotlinUClass.kt:42)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:97)
	at io.ktor.ide.oas.KtorOasStatusCodeVisitor.visitExpression(KtorOasArgumentVisitors.kt:45)
	at org.jetbrains.uast.visitor.UastVisitor.visitSimpleNameReferenceExpression(UastVisitor.kt:27)
	at org.jetbrains.uast.USimpleNameReferenceExpression.accept(USimpleNameReferenceExpression.kt:19)
	at org.jetbrains.uast.UEnumConstant.accept(UVariable.kt:148)
	at org.jetbrains.uast.internal.ImplementationUtilsKt.acceptList(implementationUtils.kt:15)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:99)
	at io.ktor.ide.oas.KtorOasStatusCodeVisitor.visitExpression(KtorOasArgumentVisitors.kt:45)
	at org.jetbrains.uast.visitor.UastVisitor.visitSimpleNameReferenceExpression(UastVisitor.kt:27)
	at org.jetbrains.uast.USimpleNameReferenceExpression.accept(USimpleNameReferenceExpression.kt:19)
	at org.jetbrains.uast.UEnumConstant.accept(UVariable.kt:148)
	at org.jetbrains.uast.internal.ImplementationUtilsKt.acceptList(implementationUtils.kt:15)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:99)
	at io.ktor.ide.oas.KtorOasStatusCodeVisitor.visitExpression(KtorOasArgumentVisitors.kt:45)
	at org.jetbrains.uast.visitor.UastVisitor.visitSimpleNameReferenceExpression(UastVisitor.kt:27)
	at org.jetbrains.uast.USimpleNameReferenceExpression.accept(USimpleNameReferenceExpression.kt:19)
	at org.jetbrains.uast.UEnumConstant.accept(UVariable.kt:148)
	at org.jetbrains.uast.internal.ImplementationUtilsKt.acceptList(implementationUtils.kt:15)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:99)
	at io.ktor.ide.oas.KtorOasStatusCodeVisitor.visitExpression(KtorOasArgumentVisitors.kt:45)
	at org.jetbrains.uast.visitor.UastVisitor.visitSimpleNameReferenceExpression(UastVisitor.kt:27)
	at org.jetbrains.uast.USimpleNameReferenceExpression.accept(USimpleNameReferenceExpression.kt:19)
	at org.jetbrains.uast.UEnumConstant.accept(UVariable.kt:148)
	at org.jetbrains.uast.internal.ImplementationUtilsKt.acceptList(implementationUtils.kt:15)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:99)
	at io.ktor.ide.oas.KtorOasStatusCodeVisitor.visitExpression(KtorOasArgumentVisitors.kt:45)
	at org.jetbrains.uast.visitor.UastVisitor.visitSimpleNameReferenceExpression(UastVisitor.kt:27)
	at org.jetbrains.uast.USimpleNameReferenceExpression.accept(USimpleNameReferenceExpression.kt:19)
	at org.jetbrains.uast.UEnumConstant.accept(UVariable.kt:148)
	at org.jetbrains.uast.internal.ImplementationUtilsKt.acceptList(implementationUtils.kt:15)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:99)
	at io.ktor.ide.oas.KtorOasStatusCodeVisitor.visitExpression(KtorOasArgumentVisitors.kt:45)
	at org.jetbrains.uast.visitor.UastVisitor.visitSimpleNameReferenceExpression(UastVisitor.kt:27)
	at org.jetbrains.uast.USimpleNameReferenceExpression.accept(USimpleNameReferenceExpression.kt:19)
	/* ... repeats 50 times or so ... */
```

This seems to have happened when I pressed "Generate Ktor OpenAPI documentation" in the IDE

**Comment by Nek-12** [comment]
I'm closing this in favor of https://youtrack.jetbrains.com/issue/KTOR-5972 to not bother you with another issue for now. I may reopen it based on the results of our investigation

**Comment by arturbosch** [comment]
hey @Nek-12 which IntelliJ version do you use?
Mainly in older IntelliJ's Kotlin compiler stacktraces are attributed to detekt, see #271
