### ISSUE TITLE
Allow configuration files with 'yaml' extension

### ISSUE THREAD

**Issue by ajordanow** [detekt/detekt-intellij-plugin#69]
Currently configuring file with yaml extension (e.g. `config.yaml`) yields an error:

```
...
Caused by: java.lang.IllegalArgumentException: Invalid config file name /Users/.../detekt/detekt-config.yaml: file does not end with .yml!
	at io.gitlab.arturbosch.detekt.api.YamlConfig$Companion.load(YamlConfig.kt:51)
	at io.gitlab.arturbosch.detekt.cli.ConfigurationsKt.parsePathConfig(Configurations.kt:58)
...
```

Plugin version: `1.0.0-RC2`

**Comment by arturbosch** [comment]
detekt 1.7.x fixes this. For now you may rename it to `config.yml`.
